language: node_js

node_js:
  - "10"

env:
  - CXX=g++-4.8 HTML_RPC_ADDRESS='http://althash:password@localhost:14889' SENDER_ADDRESS='hMZK8FNPRm54jvTLAGEs1biTCgyCkcsmna' WALLET_PASSPHRASE='password'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

cache:
  directories:
    - "node_modules"

before_install:
  - wget https://github.com/HTMLCOIN/HTMLCOIN/releases/download/v2.5.0/htmlcoin-2.5.0-linux64.tar.gz

install:
  - tar -xvzf htmlcoin-2.5.0-linux64.tar.gz
  - npm install
  - mkdir test/data/.html

script:
  - ./htmlcoin-2.5.0-linux64/bin/htmld -testnet -logevents -rpcuser=althash -rpcpassword=password -datadir=./test/data/.html & 
  - sleep 10
  - npm run test:cleanenv

after_failure:
  - cat /home/machado/build/machado-rev/hweb3.js/test/data/.html/testnet3/debug.log
